USE [BusinessSafe]

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Task' AND COLUMN_NAME = 'Discriminator')
BEGIN
	ALTER TABLE [Task] ALTER COLUMN [Discriminator] VARCHAR(150) NOT NULL
END
GO	

--//@UNDO 

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Task' AND COLUMN_NAME = 'Discrimnator')
BEGIN
	ALTER TABLE [Task] ALTER COLUMN [Discriminator] VARCHAR(50) NOT NULL
END
GO