USE [BusinessSafe]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RiskAssessment' AND COLUMN_NAME = 'Reference')
BEGIN
	ALTER TABLE [RiskAssessment]
	ALTER COLUMN [Reference] VARCHAR(50) NULL
END
GO

--//@UNDO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RiskAssessment' AND COLUMN_NAME = 'Reference')
BEGIN
	ALTER TABLE [RiskAssessment]
	ALTER COLUMN [Reference] VARCHAR(50) NOT NULL
END
GO