USE [BusinessSafe]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'PermissionsApplyToAllSites')
BEGIN
	ALTER TABLE [User]
	DROP COLUMN [PermissionsApplyToAllSites]
END
GO

--//@UNDO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'PermissionsApplyToAllSites')
BEGIN
	ALTER TABLE [User]
	ADD [PermissionsApplyToAllSites] BIT NULL
END
GO