USE [BusinessSafe]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'GeneralRiskAssessment')
BEGIN
	CREATE TABLE [dbo].[GeneralRiskAssessment](
		[Id] [bigint] NULL
	) ON [PRIMARY]
END

--//@UNDO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'GeneralRiskAssessment')
BEGIN
	DROP TABLE [GeneralRiskAssessment];
END