USE [BusinessSafe]
GO

IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'GeneralRiskAssessment')
BEGIN
	GRANT SELECT, INSERT, DELETE, UPDATE ON [GeneralRiskAssessment] TO [AllowAll]
END

--//@UNDO 
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'GeneralRiskAssessment')
BEGIN
	REVOKE SELECT, INSERT, DELETE, UPDATE ON [GeneralRiskAssessment] FROM [AllowAll]
END
GO