USE [BusinessSafe]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RiskAssessment' AND COLUMN_NAME = 'Title' AND CHARACTER_MAXIMUM_LENGTH = 200)
BEGIN
	ALTER TABLE [dbo].[RiskAssessment]
	ALTER COLUMN [Title] [nvarchar](250)
END
GO

--//@UNDO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'RiskAssessment' AND COLUMN_NAME = 'Title' AND CHARACTER_MAXIMUM_LENGTH = 250)
BEGIN
	ALTER TABLE [dbo].[RiskAssessment]
	ALTER COLUMN [Title] [nvarchar](200)
END
GO
