USE [BusinessSafe]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FireRiskAssessment' AND COLUMN_NAME = 'Location' AND CHARACTER_MAXIMUM_LENGTH = 500)
BEGIN
	ALTER TABLE [dbo].[FireRiskAssessment]
	ALTER COLUMN [Location] [nvarchar](250)
END
GO

--//@UNDO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FireRiskAssessment' AND COLUMN_NAME = 'Title' AND CHARACTER_MAXIMUM_LENGTH = 250)
BEGIN
	ALTER TABLE [dbo].[FireRiskAssessment]
	ALTER COLUMN [Location] [nvarchar](500)
END
GO