USE [BusinessSafe]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FireRiskAssessment' AND COLUMN_NAME = 'ElectricityEmergencyShutOff' AND CHARACTER_MAXIMUM_LENGTH = 200)
BEGIN
	ALTER TABLE [dbo].[FireRiskAssessment]
	ALTER COLUMN [ElectricityEmergencyShutOff] [nvarchar](500)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FireRiskAssessment' AND COLUMN_NAME = 'GasEmergencyShutOff' AND CHARACTER_MAXIMUM_LENGTH = 200)
BEGIN
	ALTER TABLE [dbo].[FireRiskAssessment]
	ALTER COLUMN [GasEmergencyShutOff] [nvarchar](500)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FireRiskAssessment' AND COLUMN_NAME = 'WaterEmergencyShutOff' AND CHARACTER_MAXIMUM_LENGTH = 200)
BEGIN
	ALTER TABLE [dbo].[FireRiskAssessment]
	ALTER COLUMN [WaterEmergencyShutOff] [nvarchar](500)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FireRiskAssessment' AND COLUMN_NAME = 'OtherEmergencyShutOff' AND CHARACTER_MAXIMUM_LENGTH = 200)
BEGIN
	ALTER TABLE [dbo].[FireRiskAssessment]
	ALTER COLUMN [OtherEmergencyShutOff] [nvarchar](500)
END
GO

--//@UNDO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FireRiskAssessment' AND COLUMN_NAME = 'ElectricityEmergencyShutOff' AND CHARACTER_MAXIMUM_LENGTH = 500)
BEGIN
	ALTER TABLE [dbo].[FireRiskAssessment]
	ALTER COLUMN [ElectricityEmergencyShutOff] [nvarchar](200)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FireRiskAssessment' AND COLUMN_NAME = 'GasEmergencyShutOff' AND CHARACTER_MAXIMUM_LENGTH = 500)
BEGIN
	ALTER TABLE [dbo].[FireRiskAssessment]
	ALTER COLUMN [GasEmergencyShutOff] [nvarchar](200)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FireRiskAssessment' AND COLUMN_NAME = 'WaterEmergencyShutOff' AND CHARACTER_MAXIMUM_LENGTH = 500)
BEGIN
	ALTER TABLE [dbo].[FireRiskAssessment]
	ALTER COLUMN [WaterEmergencyShutOff] [nvarchar](200)
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FireRiskAssessment' AND COLUMN_NAME = 'OtherEmergencyShutOff' AND CHARACTER_MAXIMUM_LENGTH = 500)
BEGIN
	ALTER TABLE [dbo].[FireRiskAssessment]
	ALTER COLUMN [OtherEmergencyShutOff] [nvarchar](200)
END
GO