USE [BusinessSafe]
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Answer' AND COLUMN_NAME = 'FireAnswerSetId')
BEGIN
	ALTER TABLE [Answer]
	ADD [FireAnswerSetId] [bigint] NULL
END
GO	

--//@UNDO 

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Answer' AND COLUMN_NAME = 'FireAnswerSetId')
BEGIN
	ALTER TABLE [Answer]
	DROP COLUMN [FireAnswerSetId]
END
GO