USE [BusinessSafe]
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FireAnswerSet' AND COLUMN_NAME = 'ReviewGeneratedFromId')
BEGIN
	ALTER TABLE [FireAnswerSet]
	ADD [ReviewGeneratedFromId] [bigint] NULL
END
GO	

--//@UNDO 

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'FireAnswerSet' AND COLUMN_NAME = 'ReviewGeneratedFromId')
BEGIN
	ALTER TABLE [FireAnswerSet]
	DROP COLUMN [ReviewGeneratedFromId]
END
GO