USE[BusinessSafe]
GO

UPDATE [Question] SET [ListOrder] = 1 WHERE [SectionId] = 35 AND [ListOrder] = 1
UPDATE [Question] SET [ListOrder] = 2 WHERE [SectionId] = 35 AND [ListOrder] = 2
UPDATE [Question] SET [ListOrder] = 3 WHERE [SectionId] = 35 AND [ListOrder] = 3
UPDATE [Question] SET [ListOrder] = 4 WHERE [SectionId] = 35 AND [ListOrder] = 4
UPDATE [Question] SET [ListOrder] = 5 WHERE [SectionId] = 35 AND [ListOrder] = 5
UPDATE [Question] SET [ListOrder] = 6 WHERE [SectionId] = 36 AND [ListOrder] = 1
UPDATE [Question] SET [ListOrder] = 7 WHERE [SectionId] = 36 AND [ListOrder] = 2
UPDATE [Question] SET [ListOrder] = 8 WHERE [SectionId] = 36 AND [ListOrder] = 3
UPDATE [Question] SET [ListOrder] = 9 WHERE [SectionId] = 36 AND [ListOrder] = 4
UPDATE [Question] SET [ListOrder] = 10 WHERE [SectionId] = 36 AND [ListOrder] = 5
UPDATE [Question] SET [ListOrder] = 11 WHERE [SectionId] = 36 AND [ListOrder] = 6
UPDATE [Question] SET [ListOrder] = 12 WHERE [SectionId] = 36 AND [ListOrder] = 7
UPDATE [Question] SET [ListOrder] = 13 WHERE [SectionId] = 36 AND [ListOrder] = 8
UPDATE [Question] SET [ListOrder] = 14 WHERE [SectionId] = 36 AND [ListOrder] = 9
UPDATE [Question] SET [ListOrder] = 15 WHERE [SectionId] = 37 AND [ListOrder] = 1
UPDATE [Question] SET [ListOrder] = 16 WHERE [SectionId] = 37 AND [ListOrder] = 2
UPDATE [Question] SET [ListOrder] = 17 WHERE [SectionId] = 37 AND [ListOrder] = 3
UPDATE [Question] SET [ListOrder] = 18 WHERE [SectionId] = 37 AND [ListOrder] = 4
UPDATE [Question] SET [ListOrder] = 19 WHERE [SectionId] = 38 AND [ListOrder] = 1
UPDATE [Question] SET [ListOrder] = 20 WHERE [SectionId] = 38 AND [ListOrder] = 2
UPDATE [Question] SET [ListOrder] = 21 WHERE [SectionId] = 38 AND [ListOrder] = 3
UPDATE [Question] SET [ListOrder] = 22 WHERE [SectionId] = 38 AND [ListOrder] = 4
UPDATE [Question] SET [ListOrder] = 23 WHERE [SectionId] = 38 AND [ListOrder] = 5
UPDATE [Question] SET [ListOrder] = 24 WHERE [SectionId] = 38 AND [ListOrder] = 6
UPDATE [Question] SET [ListOrder] = 25 WHERE [SectionId] = 38 AND [ListOrder] = 7
UPDATE [Question] SET [ListOrder] = 26 WHERE [SectionId] = 38 AND [ListOrder] = 8
UPDATE [Question] SET [ListOrder] = 27 WHERE [SectionId] = 38 AND [ListOrder] = 9
UPDATE [Question] SET [ListOrder] = 28 WHERE [SectionId] = 38 AND [ListOrder] = 10
UPDATE [Question] SET [ListOrder] = 29 WHERE [SectionId] = 38 AND [ListOrder] = 11
UPDATE [Question] SET [ListOrder] = 30 WHERE [SectionId] = 38 AND [ListOrder] = 12
UPDATE [Question] SET [ListOrder] = 31 WHERE [SectionId] = 38 AND [ListOrder] = 13
UPDATE [Question] SET [ListOrder] = 32 WHERE [SectionId] = 38 AND [ListOrder] = 14
UPDATE [Question] SET [ListOrder] = 33 WHERE [SectionId] = 39 AND [ListOrder] = 1
UPDATE [Question] SET [ListOrder] = 34 WHERE [SectionId] = 39 AND [ListOrder] = 2
UPDATE [Question] SET [ListOrder] = 35 WHERE [SectionId] = 39 AND [ListOrder] = 3
UPDATE [Question] SET [ListOrder] = 36 WHERE [SectionId] = 40 AND [ListOrder] = 1
UPDATE [Question] SET [ListOrder] = 37 WHERE [SectionId] = 40 AND [ListOrder] = 2
UPDATE [Question] SET [ListOrder] = 38 WHERE [SectionId] = 40 AND [ListOrder] = 3
UPDATE [Question] SET [ListOrder] = 39 WHERE [SectionId] = 40 AND [ListOrder] = 4
UPDATE [Question] SET [ListOrder] = 40 WHERE [SectionId] = 40 AND [ListOrder] = 5
UPDATE [Question] SET [ListOrder] = 41 WHERE [SectionId] = 40 AND [ListOrder] = 6
UPDATE [Question] SET [ListOrder] = 42 WHERE [SectionId] = 40 AND [ListOrder] = 7
UPDATE [Question] SET [ListOrder] = 43 WHERE [SectionId] = 40 AND [ListOrder] = 8
UPDATE [Question] SET [ListOrder] = 44 WHERE [SectionId] = 41 AND [ListOrder] = 1
UPDATE [Question] SET [ListOrder] = 45 WHERE [SectionId] = 41 AND [ListOrder] = 2
UPDATE [Question] SET [ListOrder] = 46 WHERE [SectionId] = 41 AND [ListOrder] = 3
UPDATE [Question] SET [ListOrder] = 47 WHERE [SectionId] = 41 AND [ListOrder] = 4
UPDATE [Question] SET [ListOrder] = 48 WHERE [SectionId] = 41 AND [ListOrder] = 5
UPDATE [Question] SET [ListOrder] = 49 WHERE [SectionId] = 41 AND [ListOrder] = 6
UPDATE [Question] SET [ListOrder] = 50 WHERE [SectionId] = 41 AND [ListOrder] = 7
UPDATE [Question] SET [ListOrder] = 51 WHERE [SectionId] = 41 AND [ListOrder] = 8
UPDATE [Question] SET [ListOrder] = 52 WHERE [SectionId] = 41 AND [ListOrder] = 9
UPDATE [Question] SET [ListOrder] = 53 WHERE [SectionId] = 42 AND [ListOrder] = 1
GO
