USE[BusinessSafe]
GO

UPDATE QUESTION SET Information = 'Only such quantities as are required for the day''s production needs should be taken out of store. The remaining stock should, if small, be kept in flameproof metal cabinets and, if large, in a dedicated flammable liquids store.' WHERE ListOrder =  1 AND SectionId = 35
UPDATE QUESTION SET Information = 'The system should be monitored to ensure that waste materials including partly-used containers of paint, flammable solvents, or flammable-solvent based adhesives do not , accumulate in the workplace.' WHERE ListOrder =  2 AND SectionId = 35
UPDATE QUESTION SET Information = 'Stores for flammable liquids and stores for combustible materials should be sited at secure locations, and they should carry No Smoking signs and signs such as ''Flammable Liquid'', ''Flammable Gas'' etc. as appropriate. The arrangements for the storage of flammable liquids should conform to the guidelines published in Dangerous Substances and Explosive Atmospheres Regulations. See Guidance Notes 4-6 and 4-7.' WHERE ListOrder =  3 AND SectionId = 35
UPDATE QUESTION SET Information = 'Old and dilapidated furniture can contribute to the spread of fire. All new upholstered furniture for non-domestic use should comply with the requirements of British Standards 7176 and BS 7177.' WHERE ListOrder =  4 AND SectionId = 35
UPDATE QUESTION SET Information = 'The accumulation of rubbish and combustible waste materials is a hazard because it adds to the fire load of the building. Also, because arson, an often motiveless crime, can be prompted simply by the availability of combustible materials, their presence will increase the risk of an arson attack. All rubbish and combustible waste should be cleared from the building on a daily basis and securely stored, preferably in lockable metal skips, outside the building, away from fire exits and not under any overhanging structure.' WHERE ListOrder =  5 AND SectionId = 35
UPDATE QUESTION SET Information = 'Smoking in the workplace and premises open to the public is prohibited. It is good practice to allow smokers to use specified areas outside of the building providing those places with non- combustible, secure and stable ash trays or containers. These should be regularly emptied. A suitable fire extinguisher should be located nearby. Any structure provided for a smoking area must be at least 50% open to comply with statutory requirements.' WHERE ListOrder =  6 AND SectionId = 36
UPDATE QUESTION SET Information = 'All processes and procedures should be reviewed in order to ensure that they are safe. Important points to consider include the following: i) Is heating or electrical equipment left on for longer than is needed? ii) Are there reminders in place to turn off all heat producing equipment at the end of the work period? iii) Could any process involving the use or production of heat be replaced by a low temperature alternative? iv) When solvent-based adhesives are in use, is the area well ventilated in order to prevent the build-up of flammable vapours? v) Could solvent-based substances be replaced by water-based alternatives?' WHERE ListOrder =  7 AND SectionId = 36
UPDATE QUESTION SET Information = 'Arson is a major cause of fires in industry and commerce; some 40% of all fires in non- domestic premises are started deliberately. Good security is probably the best protection against arson and therefore it is important to ensure that all means of access to the premises '' doors and windows '' are locked at all times when the building is unoccupied. All visitors to the premises should be signed in, issued with visitors'' badges, and be accompanied by their host at all times. Staff should be trained to challenge anybody whose presence or behaviour gives cause for concern and to immediately report any suspicious behaviour.' WHERE ListOrder =  8 AND SectionId = 36
UPDATE QUESTION SET Information = 'Cost-effective measures that could be considered include: i) improving perimeter security ''mending broken fencing, ii) not leaving ladders, or other materials such as piles of palettes that invite people to scale fences, ii) introducing perimeter lighting and the lighting of all external doors, iii) installing a CCTV system, iv) installing an intruder alarm system, v) fitting letterboxes with fireproof metal boxes, vi) training post room staff in the spotting and handling of suspicious packages.' WHERE ListOrder =  9 AND SectionId = 36
UPDATE QUESTION SET Information = 'Trailing cables and leads that cross gangways or work areas can be damaged by being walked on or subject to heavy external loads. Best practice is to avoid the use of training leads or to route them where they will not be at risk of damage. Where their use is unavoidable they should be run in protective flexible plastic or rubber sheathing. This will also reduce the tripping hazard.' WHERE ListOrder =  10 AND SectionId = 36
UPDATE QUESTION SET Information = 'Smoking in the workplace and premises open to the public is prohibited. It is good practice to allow smokers to use specified areas outside of the building providing those places with non-combustible, secure and stable ash trays or containers. These should be regularly emptied. A suitable fire extinguisher should be located nearby. Any structure provided for a smoking area , must be at least 50% open to comply with statutory requirements.' WHERE ListOrder =  11 AND SectionId = 36
UPDATE QUESTION SET Information = 'All processes and procedures should be reviewed in order to ensure that they are safe. Important points to consider include the following: i) Is heating or electrical equipment left on , for longer than is needed? ii) Are there reminders in place to turn off all heat producing equipment at the end of the work period? iii) Could any process involving the use or , production of heat be replaced by a low temperature alternative? iv) When solvent-based adhesives are in use, is the area well ventilated in order to prevent the build-up of flammable, vapours? v) Could solvent-based substances be replaced by water-based alternatives?' WHERE ListOrder =  12 AND SectionId = 36
UPDATE QUESTION SET Information = 'Arson is a major cause of fires in industry and commerce; some 40% of all fires in non-domestic premises are started deliberately. Good security is probably the best protection against arson and therefore it is important to ensure that all means of access to the premises ''doors and windows'' are locked at all times when the building is unoccupied. All visitors to the premises should be signed in, issued with visitors'' badges, and be accompanied by their host at all times. Staff should be trained to challenge anybody whose presence or behaviour gives , cause for concern and to immediately report any suspicious behaviour.' WHERE ListOrder =  13 AND SectionId = 36
UPDATE QUESTION SET Information = 'Cost-effective measures that could be considered include: i) improving perimeter security ''mending broken fencing, ii) not leaving ladders, or other materials such as piles of palettes that invite people to scale fences, ii) introducing perimeter lighting and the lighting of all external doors, iii) installing a CCTV system, iv) installing an intruder alarm system, v) fitting letterboxes with fireproof metal boxes, vi) training post room staff in the spotting and , handling of suspicious packages.' WHERE ListOrder =  14 AND SectionId = 36
UPDATE QUESTION SET Information = 'You should have an emergency evacuation procedure to cover fire related or other emergencies such as a bomb threat or gas leak. The procedure should SET out what your managers and workforce should do, if the event of a fire or other emergency, to safely evacuate the premises and get to a place of relative safety. The emergency procedure should always be based on your risk assessment of the premises and be explained to the workforce. In simple premises the emergency plan may be no more than a basic fire action notice. In more complex premises it will need to be detailed and its preparation is likely to require the involvement of others; for example a landlord and other tenants or occupants of a shared building.' WHERE ListOrder =  15 AND SectionId = 37
UPDATE QUESTION SET Information = 'Disabled (remember that disability may be physical or mental) employees, visitors or clients may require additional assistance to escape in the event of fire. It is essential that their needs are considered when an emergency plan is developed. In simple cases where premises are small, single storey and escape routes are short and obvious special arrangements may not be necessary. Where the premises are complex or multi-storeyed, or occupants have severe disability and wouldn''t be able to safely evacuate at the same time as others special arrangement will be required. ' WHERE ListOrder =  16 AND SectionId = 37
UPDATE QUESTION SET Information = 'Disabled and vulnerable people who can evacuate at the same time or speed as others will not need a personal emergency evacuation plan (PEEP). If they are slow moving and likely to hold up the evacuation others or to struggle in getting out of the building in good time (less than 2.5 minutes in a normal risk building) they will need a PEEP. Guidance Note 2-3 explains this requirement in detail and includes a form (form PEEP) which can be used for the preparation of an individual PEEP.' WHERE ListOrder =  17 AND SectionId = 37
UPDATE QUESTION SET Information = 'Whenever a PEEP is prepared it must be tested and practiced. The people nominated to act as companion(s) to the PEEP holder must be aware of the plan and arrangements. Guidance Note 2-3 gives advice on practicing PEEPs.' WHERE ListOrder =  18 AND SectionId = 37
UPDATE QUESTION SET Information = 'The principal structural means for limiting the spread of fire is compartmentalisation ''dividing the building into compartments that are separated from each other by fire resistant walls and doors. The integrity of the compartmentalisation will be compromised if the fire doors have been badly hung, or if the compartmentalisation does not extend into the floor and ceiling voids that are created by suspended floors and ceilings. Penetration of fire walls by ducting or building services greatly reduces the effectiveness of the wall, unless the spaces between the ducting or services and the hole through which they pass are completely filled with fire- resistant stopping.' WHERE ListOrder =  19 AND SectionId = 38
UPDATE QUESTION SET Information = 'In any building where construction or modification has been undertaken in conformity with the requirements of the Building Regulations, the number and size of the exits from the building will be sufficient for the use to which the building is put. Any proposed change of use and any proposed structural changes must be reported to the Fire Authority, and all exits must be totally free from obstruction on both sides of the door. Exit doors must never be locked shut during working hours. There are tables linked to this advice on sheet 2.' WHERE ListOrder =  20 AND SectionId = 38
UPDATE QUESTION SET Information = 'A place of safety is a place beyond the building in which a person is no longer in danger from fire. The designated place of safety must not be a dead-end situation from which people are unable to move further away from the building.' WHERE ListOrder =  21 AND SectionId = 38
UPDATE QUESTION SET Information = 'Gangways and escape routes must never be obstructed. Obstructions such as unwanted furniture, unattended tea trolleys, wheelchairs, coat racks, stocks of stationery, cleaning products and equipment, newly delivered goods or goods awaiting collection, reduce the available width of escape routes and make it more difficult to quickly and safely evacuate people in the event of fire. Sources of heat or electrical equipment such as portable heaters, automatic vending machines, photocopiers etc. should not be sited on escape routes.' WHERE ListOrder =  22 AND SectionId = 38
UPDATE QUESTION SET Information = 'Changes of level, electrical extension leads, loose or damaged flooring tiles, and small items '' such as empty drink cans or contractors'' tools '' left on the floor are all capable of causing people to trip. Changes of level should be indicated by use of warning tape. Wet floors and loose mats or runners constitute slipping hazards.' WHERE ListOrder =  23 AND SectionId = 38
UPDATE QUESTION SET Information = 'Loose handrails, raised or loose floor tiles, and damaged nosings on steps may all cause people to trip whilst escaping from fire; on a staircase this could have disastrous consequences.' WHERE ListOrder =  24 AND SectionId = 38
UPDATE QUESTION SET Information = 'Final exit doors must always remain unlocked whenever the premises are in use. If, for reasons of security, final exit doors have to be locked, they should be secured by a panic-release type. In low risk premises break-glass bolts (Redlam bolts), which are released by breaking a glass tube with a small hammer, may be an acceptable way of keeping a fire exit door securely shut, provided that clear instructions as to how to release the bolt are displayed on or adjacent to the door and that a suitable hammer is attached by a chain that is anchored on or adjacent to the door. Where security is important doors fitted with panic bars can be alarmed.' WHERE ListOrder =  25 AND SectionId =38
UPDATE QUESTION SET Information = 'Panic release bars are the best practice preferred option. However in low risk premises break- glass bolts (Redlam bolts), which are released by breaking a glass tube with a small hammer, may be an acceptable way of keeping a fire exit door securely shut, provided that clear instructions as to how to release the bolt are displayed on or adjacent to the door and that a suitable hammer is attached by a chain that is anchored on or adjacent to the door. Where security is important doors fitted with panic bars can be alarmed.' WHERE ListOrder =  26 AND SectionId = 38
UPDATE QUESTION SET Information = 'Doors on escape routes should normally open in the direction of travel. They must do so if they lead from an area from which more than 50 people may be required to escape, or if they lead from an area of high fire risk such as, for example, a kitchen.' WHERE ListOrder =  27 AND SectionId = 38
UPDATE QUESTION SET Information = 'All fire doors should carry a sign, on both faces of each leaf, bearing the legend ''Fire Door Keep Shut'', ''Automatic Fire Door Keep Clear'', or ''Fire Door Keep Locked'' (this last sign applies to fire resistant doors on cupboards or service shafts that open onto protected escape routes) as appropriate. Fire doors are the principal means of preventing flames, smoke, and toxic gases from spreading into escape routes, but they are only effective if they remain shut at all times (except when people are using the door). All employees must be made aware that practices such as the use of wedges, doorstops etc. to hold fire doors open is a serious offence (in law) because it puts people''s lives at risk in the event of fire. If any Fire Doors are held open on electro-magnets linked to a fire alarm system they should be regularly checked, faults identified should be reported and repaired.' WHERE ListOrder =  28 AND SectionId = 38
UPDATE QUESTION SET Information = 'Faulty self-closing devices or those in which the tension has been incorrectly SET will not automatically close fire doors. This will put lives at risk in the event of fire. Employees should be made aware of the importance of reporting any self-closing devices that are not operating correctly. The operation of any Fire Doors which are held open on electro-magnets linked to a fire alarm system should be regularly checked; faults identified should be reported and , repaired.' WHERE ListOrder =  29 AND SectionId = 38
UPDATE QUESTION SET Information = 'Escape routes that do not constitute a normal means of leaving a building should be properly signed with signs conforming to statutory requirements making use of pictograms employing a running man, open door, and directional arrows. These pictogram signs may be augmented by text. Signs using text alone are not acceptable.' WHERE ListOrder =  30 AND SectionId = 38
UPDATE QUESTION SET Information = 'Where fire escape routes need artificial lighting this should be battery protected emergency escape lighting, because the mains electricity supply may fail in a fire. In general, this type of lighting is always required in underground parts of the premises, in windowless parts of the premises, in core stairways or those serving storeys more than 30m above ground level, in internal corridors more than 30m long, and in open plan office areas of more than 60m2. Emergency escape lighting should conform to the requirements of BS 5266 Part 1 and be regularly maintained.' WHERE ListOrder =  31 AND SectionId = 38
UPDATE QUESTION SET Information = 'Emergency escape lighting should be installed and maintained according to the recommendations of BS 5266 Part 1. See Guidance Note 2-2.' WHERE ListOrder =  32 AND SectionId = 38
UPDATE QUESTION SET Information = 'Portable fire extinguishers are probably the commonest type of fire fighting equipment to be found in industrial and commercial premises. In a single storey premise the correct number of water extinguishers to tackle Class A fires (fires involving combustible solids such as paper, wood, cloth, plastics etc.) can be determined from its fire rating. In a multi storey building this is done floor by floor. The fire rating is found by multiplying the floor area of the premises or the building level in M2 by 0.065. Thus for a floor area of 200M2 the fire rating is 200 x 0.065 = 13. A 9 litre water extinguisher has a fire rating of 13 therefore one 9 litre water extinguisher will be required for every 200M2 of floor area. For special risks such as fires involving live electrical equipment, a suitable extinguisher should provide carbon dioxide or dry powder, near to the risk. In general fire extinguishers should be located and operated according to the following points: i) On escape routes; ii) Hung so that carrying handle is 1 metre from floor, 1.5 metres for smaller units without hoses; iii) Two extinguishers per storey; iv) Not less than one extinguisher per 200 square metres; vi) Adjacent to risk, but not too close; vii) In multi-storey buildings in the same position on each storey; viii) In groups forming fire points; ix) Away from extremes in temperature; x) All extinguishers should operate by the same method; xi) Occupants must be capable of handling the extinguishers provided; xii) Be appropriate for the specific fire hazard (i.e. the material present) xiii) The distance a person would have to travel to reach an extinguisher should not be more than 30m. If for any reason extinguishers are placed in positions hidden from direct view, their location should be indicated by suitable signs. Where hose reels are provided they should be located where they are conspicuous and always accessible such as in corridors.' WHERE ListOrder =  33 AND SectionId = 39
UPDATE QUESTION SET Information = 'Generally, extinguishers should be located at exits from buildings, rooms or storeys, in corridors that form parts of escape routes, and on landings. Extinguishers for special risks such as electrical fires, flammable liquid fires, or cooking oil fires should be located near the risk. All extinguishers and fire blankets should be located so as to be both conspicuous and readily accessible. Ideally, they should be mounted on either wall brackets or floor stands. It should never be necessary to travel more than 30m from a fire in order to reach an extinguisher.' WHERE ListOrder =  34 AND SectionId = 39
UPDATE QUESTION SET Information = 'The authorities recommend that routine examinations of extinguishers should be carried out on a weekly basis by members of the workforce, and it is a requirement of BS 5306 Part 8 2000 that more detailed maintenance procedures be carried out by a "competent person" on an annual basis.' WHERE ListOrder =  35 AND SectionId = 39
UPDATE QUESTION SET Information = 'A properly installed and maintained automatic fire detection and alarm system will give the earliest possible warning of fire, and significantly reduce the risk to life and property in the event of fire. The fire alarm should be audible in every part of the premises including toilets, storerooms and any parts that are rarely used.' WHERE ListOrder =  36 AND SectionId = 40
UPDATE QUESTION SET Information = 'The correct operation of a properly maintained system will greatly reduce the incidence of false alarms and unnecessary calls to the fire service. As well as wasting the time of fire service personnel, repeated false alarms may encourage the workforce to dismiss a genuine alarm as being "yet another false alarm".' WHERE ListOrder =  37 AND SectionId = 40
UPDATE QUESTION SET Information = 'The fire detection and alarm system should be maintained according to the recommendations of BS 5839 Part 1, which recommends a regime of testing that includes weekly testing of the fire alarm.' WHERE ListOrder =  38 AND SectionId = 40
UPDATE QUESTION SET Information = 'Fire alarm operating points should be adjacent to exit routes and final exit doors so that they can be operated without placing anyone at risk. It should always be possible to call the emergency services without putting anyone at risk from having to find a phone from which to make a 999 call. Ideally there should be automatic smoke or fire detection linked to an automatic call to a 24 hour call centre. This will usually detect the presence of a fire in its very early stages, will allow early evacuation of the premises and may also have the benefit of limiting fire damage.' WHERE ListOrder =  39 AND SectionId = 40
UPDATE QUESTION SET Information = 'Manual fire alarm call points should be mounted in conspicuous positions on exit routes, on staircase landings, and at final exits. Items such as coat racks, potted plants etc. should not be allowed to obscure the presence of a call point, or to hinder easy access to it.' WHERE ListOrder =  40 AND SectionId = 40
UPDATE QUESTION SET Information = 'In high risk premises this is a sensible control measure and may be required as part of a fire risk insurance policy. Fire detection and alarm systems are designed to protect either life or property. Fire safety law is primarily concerned with the protection of life and, as a consequence, in many workplaces the system installed is one designed for life safety. If property is to be protected, the system must be monitored 24 hours a day so as to cover the , times when there are no people present.' WHERE ListOrder =  41 AND SectionId = 40
UPDATE QUESTION SET Information = 'By connecting the FDA system to a 24 hours monitoring service, even a basic life protection system can effectively be upgraded to a property protection system. The rapid response by the fire brigade, enabled by a monitoring service, will do much to minimise fire damage to buildings, stock, plant and machinery.' WHERE ListOrder =  42 AND SectionId = 40
UPDATE QUESTION SET Information = 'Fixed fire-fighting installations such as automatic sprinkler systems, halon (or halon replacement) flooding systems in computer suites, automatic foam systems in oil-fired boiler rooms, and wet chemical drenching systems installed in the hoods above commercial deep fat fryers, all require regular maintenance by specially trained personnel if they are to be relied upon to provide the protection for which they were designed. Modern automatic fire detection systems are extremely complex and must also be regularly tested and maintained by suitably qualified personnel. British Standards SET out appropriate testing and maintenance regimes. See Guidance Note 2-2.' WHERE ListOrder =  43 AND SectionId = 40
UPDATE QUESTION SET Information = 'Employers give their employees health and safety training and this should include general fire safety. Employees must know: i) How to operate the fire alarm system, ii) How to use the fire fighting equipment provided, iii) How to call the fire brigade, iv) The location and use of the escape routes, v) The location of the assembly point and vi) How to assist visitors and members of the public in evacuating the workplace.' WHERE ListOrder =  44 AND SectionId = 41
UPDATE QUESTION SET Information = 'Insurance companies employ fire surveyors who have experience in all aspects of fire safety including the installation and maintenance of sprinkler systems, automatic fire detection and alarm systems, fixed fire fighting installations etc. and they are always happy to offer free advice on such matters.' WHERE ListOrder =  45 AND SectionId = 41
UPDATE QUESTION SET Information = 'Once the findings of the Fire Risk Assessment have been recorded they, and any recommendations that have been made in the light of the findings, should be brought to the attention of senior members of management, and also to members of staff or their representatives.' WHERE ListOrder =  46 AND SectionId = 41
UPDATE QUESTION SET Information = 'If you have prepared a formal report it should be brought to the attention of senior managers and then made available to staff or their representatives.' WHERE ListOrder =  47 AND SectionId = 41
UPDATE QUESTION SET Information = 'Any risks identified in your fire risk assessment should be brought to the attention of other employers and occupants of the premises.' WHERE ListOrder =  48 AND SectionId = 41
UPDATE QUESTION SET Information = 'Your findings, and any formal report that you have made, should be brought to the attention of the owner or landlord of the premises, because they may need to provide or approve any changes to systems or services that you have recommended.' WHERE ListOrder =  49 AND SectionId = 41
UPDATE QUESTION SET Information = 'A comprehensive emergency plan should be drawn up. It should include the action to be taken by staff in the event of fire, the evacuation procedure (including arrangements for the evacuation of disabled staff or visitors), the location of the assembly points and the arrangements for calling the Fire Authority. The plan should make clear who is to be responsible for the implementation of its various parts. To ensure its long term effectiveness, it should be practiced regularly, then reviewed and updated in the light of any shortcomings revealed in practice.' WHERE ListOrder =  50 AND SectionId = 41
UPDATE QUESTION SET Information = 'In larger organisations, especially those with more than one building on the site, a copy of the emergency plan should be lodged at the gate house at reception or other suitable place agreed with the fire authority.' WHERE ListOrder =  51 AND SectionId = 41
UPDATE QUESTION SET Information = 'Fire Action Notices (form FAN) should be displayed in prominent positions throughout your premises.' WHERE ListOrder =  52 AND SectionId = 41
UPDATE QUESTION SET Information = 'The preparation of a Fire Risk Assessment is not a one-off exercise; it should be subject to regular review. Buildings and processes change over time; new materials, processes, or machinery, and structural alterations may profoundly alter the risks to which employees or others are exposed. The review of a fire risk assessment should: i) identify whether actions identified in the previous assessment has been completed; '' ii) check that all equipment is serviced and maintained according to best practice; iii) consider whether any further measures are required; iv) allocate tasks and completion dates; and vi) SET the date of the next review.' WHERE ListOrder =  53 AND SectionId = 42

--//@UNDO 

