USE [BusinessSafe]
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'DateDeleted')
BEGIN
	ALTER TABLE [User]
	ADD DateDeleted datetime NULL
END
GO

UPDATE [User] 
SET DateDeleted = LastModifiedOn
WHERE [Deleted] = 1

--//@UNDO 

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'User' AND COLUMN_NAME = 'DateDeleted')
BEGIN
	ALTER TABLE [User]
	DROP COLUMN DateDeleted
END
GO