IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Task' AND COLUMN_NAME = 'TaskCompletedBy')
BEGIN
    ALTER TABLE [Task]
    ADD [TaskCompletedBy] [uniqueidentifier] NULL
END
GO


--//@UNDO 

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Task' AND COLUMN_NAME = 'TaskCompletedBy')
BEGIN
    ALTER TABLE [Task]
    DROP COLUMN [TaskCompletedBy] 
END
GO