IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Task' AND COLUMN_NAME = 'SiteId')
BEGIN
	ALTER TABLE Task
	ADD SiteId [bigint] NULL

	ALTER TABLE [dbo].Task ADD  CONSTRAINT [DF_Task_SiteId]  DEFAULT ((0)) FOR [SiteId]
END

--//@UNDO 

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Task' AND COLUMN_NAME = 'SiteId')
BEGIN
	ALTER TABLE [dbo].Task 
	DROP CONSTRAINT [DF_Task_SiteId]
	
	ALTER TABLE Task
	DROP COLUMN [SiteId] 
	
END
