USE[BusinessSafe]
GO

UPDATE [Question] SET [Information] = 'Faulty heaters are an obvious and common source of ignition. Guards and other protective covers provided by the manufacturer must be kept in place at all times. The heaters themselves should be securely fixed in a safe position to avoid them toppling over and to avoid contact with other combustibles.' WHERE [SectionId] = 36 AND [ListOrder] = 6
UPDATE [Question] SET [Information] = 'Regular inspections are a legal requirement. Check the condition of all electric cables and that appliance are fitted with correctly rated fuses. Gas fires, equipment, supply pipes and regulators (including any portable equipment and cylinders) should be in good condition and secure.' WHERE [SectionId] = 36 AND [ListOrder] = 7
UPDATE [Question] SET [Information] = 'Electrical wiring should always comply with the Wiring Regulations or Rules. Gas installations should be properly installed and annually maintained safe for use by a Gas Safe or RGII registered installer.' WHERE [SectionId] = 36 AND [ListOrder] = 8
UPDATE [Question] SET [Information] = 'Extension leads can cause a tripping hazard and when they cause a trip may be stretched and damaged and become a potential source of ignition. For the same reason extension leads and sockets should not be overloaded.' WHERE [SectionId] = 36 AND [ListOrder] = 9
UPDATE [Question] SET [Information] = 'Arson is a major cause of fires in industry and commerce; some 40% of all fires in non-domestic premises are started deliberately. Good security is probably the best protection against arson and therefore it is important to ensure that all means of access to the premises ''doors and windows'' are locked at all times when the building is unoccupied. All visitors to the premises should be signed in, issued with visitors'' badges, and be accompanied by their host at all times. Staff should be trained to challenge anybody whose presence or behaviour gives cause for concern and to immediately report any suspicious behaviour.' WHERE [SectionId] = 36 AND [ListOrder] =  12
UPDATE [Question] SET [Information] = 'All processes and procedures should be reviewed in order to ensure that they are safe. Important points to consider include the following: i) Is heating or electrical equipment left on for longer than is needed? ii) Are there reminders in place to turn off all heat producing equipment at the end of the work period? iii) Could any process involving the use or production of heat be replaced by a low temperature alternative? iv) When solvent-based adhesives are in use, is the area well ventilated in order to prevent the build-up of flammable vapours? v) Could solvent-based substances be replaced by water-based alternatives?' WHERE [SectionId] = 36 AND [ListOrder] =  13 
UPDATE [Question] SET [Information] = 'In any building where construction or modification has been undertaken in conformity with the requirements of the Building Regulations, the number and size of the exits from the building will be sufficient for the use to which the building is put. Any proposed change of use and any proposed structural changes must be reported to the Fire Authority, and all exits must be totally free from obstruction on both sides of the door. Exit doors must never be locked shut during working hours. There are tables linked to this advice on Guidance Note 2-1.' WHERE [SectionId] = 38 AND [ListOrder] =  20
UPDATE [Question] SET [Information] = 'Employers must give their employees health and safety training and this should include general fire safety. Employees must know: i) How to operate the fire alarm system, ii) How to use the fire fighting equipment provided, iii) How to call the fire brigade, iv) The location and use of the escape routes, v) The location of the assembly point and vi) How to assist visitors and members of the public in evacuating the workplace.' WHERE [SectionId] = 41 AND [ListOrder] =  44

--//@UNDO 

