USE [BusinessSafe]
GO

BEGIN TRY
	SET IDENTITY_INSERT [ResponsibilityCategory] OFF
END TRY
BEGIN CATCH
END CATCH

SET IDENTITY_INSERT [StatutoryResponsibilityTemplate] ON

INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (1,1,1,'Fire Alarm','Fire alarm test and service','2-2',1,1, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (2,1,1,'Emergency lightning','Emergency lighting test and service.','2-2',1,2, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (3,1,1,'Fire Extinguisher','Fire extinguisher checks and maintenance.','2-2',1,2, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (4,1,1,'Fire emergency procedures','Ensure that fire emergency procedures are current, are known to all staff and practiced by formal fire drills.','2-1, 2-2',1,4, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (5,1,2,'First aid kit','Check that stocks of first aid supplies are adequate and in date.','3-1',1,3, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (6,1,2,'First aiders','Arrange for the retraining of staff who hold emergency first aid and first aid at work training certificates as they expire.','3-1',2,8, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (7,1,3,'Safer food - better business','Review records kept to meet HACCP, make adjustments to control procedures and provide any additional training shown to be necessary.','4-35',1,2, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (8,1,4,'Employer''s Liability Insurance','Ensure Policy has been renewed, is displayed or made available to employees.','1-25',2,5, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (9,1,4,'Hazard Log','Check and take action on issues raised in the Hazard Log or Safety Suggestion Scheme','1-6',3,3, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (10,1,4,'Contractor safety','1.  Review H&S compliance by contractors prior to engaging their services or adding them to a preferred contractors list.  2.  Issue a copy of the Contractor Safety Handbook to each contractor setting the health and safety standards you expect them to adopt.  Obtain receipts.','7-2',1,5, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (11,1,4,'H&S consultation','Consult with employees on matters that may affect their health and safety at work.','1-5',2,4, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (12,1,4,'Driver checks','Check licences for endorsements and private vehicles for current insurance and MoT cover','',1,5, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (13,1,4,'Periodic safety check','Routine check of continuing compliance on key health and safety issues in the workplace.  Use the appropriate Periodic Review checklist from My Documentation - BusinessSafe System ','',1,3, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (14,1,4,'Annual safety review','Annual review to check that key health and safety management functions are in place and being effectively exercised. Use Annual Review checklist from My Documentation - BusinessSafe System ','',1,5, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (15,1,5,'Gas Appliances','Check that the annual gas safety checks have been carried out and the equipment is safe to use.','3-5',2,5, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (16,1,5,'Portable electrical equipment','Check and record that portable electrical equipment and power supply leads are free from defects and remain safe for use. Depending on the outcome review the frequency required for this check.','4-1',1,5, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (17,1,5,'Lifting equipment','Check that statutory inspections of cranes, lifting machinery and lifting accessories are completed and that it remains fit for use. 6 monthly inspections for lifting accessories and equipment used for lifting people, 12 months in other cases unless a specific written scheme of examination has been prepared by a competent person.','4-17',2,4, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (18,1,5,'Lifts','Check that statutory inspections have been completed and lifts remain fit for use. 6 monthly inspections for passenger lifts, annual inspection for goods only lifts.','4-18, 4-19',2,4, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (19,1,5,'Pressure systems','Check that statutory examination and test of equipemnt that opertaes under pressure including boilers, compressed air systems autoclaves, etc are tested in accordance with a written scheme of examination. Typical intervals are 12 months for steam equipment and 24 months for compressed air systems.','4-15, 4-16',2,5, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (20,1,5,'Racking checks',NULL,'4-34',1,NULL, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (21,1,5,'Mezzanine floor safety check',NULL,'4-34',1,NULL, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (22,1,6,'Fixed electrical installation','Check that the condition of the fixed electrical installation remains safe for use by way of an inspection and test carried out by a competent electrical contractor. The normal interval for most premises is 5 years but higher risk situations require more frequent checks.','4-1',1,9, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (23,1,6,'Asbestos management','Prepare an asbestos management plan in respect of any asbestos containing materials in the building and ensure that arrangements to prevent exposure are in place. Review the plan annually.','5-16',2,5, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (24,1,6,'Legionella control',NULL,NULL,2,NULL, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (25,1,7,'Training needs','Review the training needs of both long term employees and recent starters. Arrange for the training required and ensure that it is recorded.  ','1-14',1,5, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (26,1,6,'Water temperature (scalds)','Check and record that temperature regulating valves (TRVs) are controlling water temperatures to safe temperatures that will not scald users.','3-14',1,1, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (27,1,6,'Water temperatures (legionella)','Where legionella risks are managed through water temperature control check and record that temperatures at hot and cold sentinel taps are within specification.','5-12',1,3, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (28,1,5,'Play equipment','Formally check and record that play equipment is free from damage and safe to use.','6-9, 6-10',1,1, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (29,1,4,'Annual health and safety review','Complete using checklist supplied in our Safety Management System','',1,5, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (30,2,5,'Bed rails','Check that bedrails are properly maintained and associated with the beds for which they were designed. Make sure that staff are adequately trained to use the equipment properly.','6-1',1,4, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (31,2,5,'Lifting aids','Check that any lifting aids used when handling residents or clients that are not subject to statutory test and examination are adequately maintained, free from defects and fit for continued use.','4-17',1,4, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (32,2,6,'Water temperature (scalds)','Check and record that temperature regulating valves (TRVs) are controlling water temperatures to safe temperatures that will not scald users.','3-14',1,1, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (33,2,5,'Mobility aids','Check and record that all mobility aids, wheelchairs, frames, etc are maintained and in good working order','6-2',1,4, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (34,2,6,'Infection control','Check adequacy of and compliance with our infection control policy. Check that all current employees have had relevant training and instruction.','5-4',1,NULL, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)
INSERT INTO [BusinessSafe].[dbo].[StatutoryResponsibilityTemplate]([Id], [SectorId],[ResponsibilityCategoryId],[Title],[Description],[GuidanceNote],[ResponsibilityReasonId], [TaskReoccurringTypeId],[CreatedBy],[CreatedOn],[Deleted]) VALUES (35,3,5,'Machine safety','Check that all guards and safety equipment are fitted and work as designed -  check that interlocking arrangements are functional and have not been deleted.','4-10, 4-11',1,2, N'4CC5B9B8-E335-4E27-9AA3-C48B9AA6BC4D', '2013-07-23 15:00:00.000', 0)

SET IDENTITY_INSERT [StatutoryResponsibilityTemplate] OFF


GO



