
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmployeeChecklist' AND COLUMN_NAME = 'AssessedByEmployeeId')
BEGIN
	ALTER TABLE [EmployeeChecklist]
	ADD [AssessedByEmployeeId] UNIQUEIDENTIFIER NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmployeeChecklist' AND COLUMN_NAME = 'AssessmentDate')
BEGIN
	ALTER TABLE [EmployeeChecklist]
	ADD [AssessmentDate] DATETIME NULL
END

--//@UNDO 


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmployeeChecklist' AND COLUMN_NAME = 'AssessedByEmployeeId')
BEGIN
	ALTER TABLE [EmployeeChecklist]
	DROP COLUMN [AssessedByEmployeeId] 
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'EmployeeChecklist' AND COLUMN_NAME = 'AssessmentDate')
BEGIN
	ALTER TABLE [EmployeeChecklist]
	DROP COLUMN [AssessmentDate] 
END