IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'EscalationOffWorkReminder')
BEGIN
	CREATE TABLE [dbo].[EscalationOffWorkReminder](
		[Id] [int] IDENTITY(1,1) NOT NULL,
		[AccidentRecordId] [bigint] NOT NULL,
		[OffWorkReminderEmailSentDate] [datetime] NOT NULL,
		

		CONSTRAINT [PK_EscalationOffWorkReminder] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

	GRANT SELECT, INSERT, DELETE, UPDATE ON [EscalationOffWorkReminder] TO AllowAll

END

--//@UNDO
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'EscalationOffWorkReminder')
BEGIN
	DROP TABLE [EscalationOffWorkReminder];
END
