USE [BusinessSafe]
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = '[AccidentRecord]' AND COLUMN_NAME = 'IsOpen')
BEGIN
	ALTER TABLE	AccidentRecord		
	ADD IsOpen bit NOT NULL default 1
END
GO

--//@UNDO 
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = '[AccidentRecord]' AND COLUMN_NAME = 'IsOpen')
BEGIN
	ALTER TABLE	AccidentRecord
	DROP COLUMN IsOpen
END