
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SafeCheckIndustry')
BEGIN
	CREATE TABLE [dbo].[SafeCheckIndustry](
		[Id] [uniqueidentifier] NOT NULL DEFAULT NEWID(),	
		[Name] text,
		
	CONSTRAINT [PK_SafeCheckIndustry] PRIMARY KEY CLUSTERED 
	(
		[Id] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	GRANT SELECT, INSERT, UPDATE ON [SafeCheckIndustry] TO AllowAll
	GRANT SELECT, INSERT, UPDATE ON [SafeCheckIndustry] TO AllowSelectInsertUpdate
END
GO

--//@UNDO 

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'SafeCheckIndustry')
BEGIN
	DROP TABLE [dbo].[SafeCheckIndustry]
END
GO