USE [BusinessSafe]
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ActionPlan' AND COLUMN_NAME = 'CompanyId')
BEGIN
	ALTER TABLE	ActionPlan		
		ADD CompanyId bigint null
	
END
GO

--//@UNDO 

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'ActionPlan' AND COLUMN_NAME = 'CompanyId')
BEGIN
	ALTER TABLE	ActionPlan
		DROP COLUMN CompanyId
END