IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Task' AND COLUMN_NAME = 'ActionId')
BEGIN
	ALTER TABLE Task
	ADD ActionId [bigint] NULL

	ALTER TABLE [dbo].Task ADD  CONSTRAINT [DF_Task_ActionId]  DEFAULT ((0)) FOR [ActionId]
END

--//@UNDO 

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Task' AND COLUMN_NAME = 'ActionId')
BEGIN
	ALTER TABLE [dbo].Task 
	DROP CONSTRAINT [DF_Task_ActionId]
	
	ALTER TABLE Task
	DROP COLUMN [ActionId] 
	
END
