USE [BusinessSafe]
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SafeCheckCheckList' AND COLUMN_NAME = 'ChecklistCreatedBy')
BEGIN
	ALTER TABLE SafeCheckCheckList ADD ChecklistCreatedBy nvarchar(50) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SafeCheckCheckList' AND COLUMN_NAME = 'ChecklistCreatedOn')
BEGIN
	ALTER TABLE SafeCheckCheckList ADD ChecklistCreatedOn datetime NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SafeCheckCheckList' AND COLUMN_NAME = 'ChecklistCompletedBy')
BEGIN
	ALTER TABLE SafeCheckCheckList ADD ChecklistCompletedBy nvarchar(50) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SafeCheckCheckList' AND COLUMN_NAME = 'ChecklistCompletedOn')
BEGIN
	ALTER TABLE SafeCheckCheckList ADD ChecklistCompletedOn datetime NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SafeCheckCheckList' AND COLUMN_NAME = 'ChecklistSubmittedBy')
BEGIN
	ALTER TABLE SafeCheckCheckList ADD ChecklistSubmittedBy nvarchar(50) NULL
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SafeCheckCheckList' AND COLUMN_NAME = 'ChecklistSubmittedOn')
BEGIN
	ALTER TABLE SafeCheckCheckList ADD ChecklistSubmittedOn datetime NULL
END

GO
--//@UNDO 
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SafeCheckCheckList' AND COLUMN_NAME = 'ChecklistCreatedBy')
BEGIN
	ALTER TABLE SafeCheckCheckList DROP COLUMN ChecklistCreatedBy 
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SafeCheckCheckList' AND COLUMN_NAME = 'ChecklistCreatedOn')
BEGIN
	ALTER TABLE SafeCheckCheckList DROP COLUMN ChecklistCreatedOn 
END


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SafeCheckCheckList' AND COLUMN_NAME = 'ChecklistCompletedBy')
BEGIN
	ALTER TABLE SafeCheckCheckList DROP COLUMN ChecklistCompletedBy 
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SafeCheckCheckList' AND COLUMN_NAME = 'ChecklistCompletedOn')
BEGIN
	ALTER TABLE SafeCheckCheckList DROP COLUMN ChecklistCompletedOn 
END


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SafeCheckCheckList' AND COLUMN_NAME = 'ChecklistSubmittedBy')
BEGIN
	ALTER TABLE SafeCheckCheckList DROP COLUMN ChecklistSubmittedBy 
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SafeCheckCheckList' AND COLUMN_NAME = 'ChecklistSubmittedOn')
BEGIN
	ALTER TABLE SafeCheckCheckList DROP COLUMN ChecklistSubmittedOn 
END

GO