USE [BusinessSafe]
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Action' AND COLUMN_NAME = 'ActionPlanId')
BEGIN
	
	ALTER TABLE [Action] ALTER COLUMN ActionPlanId bigint NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Action' AND COLUMN_NAME = 'AssignedTo')
BEGIN
	
	ALTER TABLE [Action] ALTER COLUMN AssignedTo uniqueidentifier NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Action' AND COLUMN_NAME = 'DueDate')
BEGIN
	
	ALTER TABLE [Action] ALTER COLUMN DueDate datetime NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Timescale' AND COLUMN_NAME = 'Name')
BEGIN	
	UPDATE Timescale SET Name = 'One Month' where Id = 1
END

GO
--//@UNDO 
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Action' AND COLUMN_NAME = 'ActionPlanId')
BEGIN
	
	ALTER TABLE [Action] ALTER COLUMN ActionPlanId bigint NOT NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Action' AND COLUMN_NAME = 'AssignedTo')
BEGIN
	
	ALTER TABLE [Action] ALTER COLUMN AssignedTo uniqueidentifier NOT NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Action' AND COLUMN_NAME = 'DueDate')
BEGIN
	
	ALTER TABLE [Action] ALTER COLUMN DueDate datetime NOT NULL
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Timescale' AND COLUMN_NAME = 'Name')
BEGIN	
	UPDATE Timescale SET Name = 'Mone Month' where Id = 1
END