USE [BusinessSafe]
GO 


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_CATALOG = 'BusinessSafe' AND TABLE_NAME = 'Action' AND COLUMN_NAME = 'Status')
BEGIN
	ALTER TABLE Action
	DROP COLUMN Status
END
GO

--//@UNDO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_CATALOG = 'BusinessSafe' AND TABLE_NAME = 'Action' AND COLUMN_NAME = 'Status')
BEGIN
	ALTER TABLE Action
	ADD Status NVARCHAR(200) NULL
END
GO
