USE [BusinessSafe]
GO

INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Slip, Trip and Fall Incidents', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)     
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Slip. Trip and Fall Outside Building', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Sprains / Strains / Dislocations in Gymnasium', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Sprains / Strains / Dislocations in Studios', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Sprains / Strains / Dislocations in Pool Area', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Manual Handling Incident', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Person Falling From Height', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Person Struck by a Falling Moving Object', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Pool Plant Room Chemical Incident', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Cardiovascular Equipment Injury', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Eye Injury', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Head Strike', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Cut / Laceration Injury', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Employee Ill health Issue', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Member / Guest Ill Health Issue', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Sauna / Steam room / Spa Over Exposure', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Free Weight Hand / Finger / Toe Injuries', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Burns from Showers / Steam Room / Sauna / Spa', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Burns from Kitchen / Other', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Feeling Faint / Collapsed (low blood sugar / overexertion)', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Sports Related Injury (e.g. 5-a-side football)', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Spin Class Injury', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Trapped Hand / Fingers in Doors / Others', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)
INSERT INTO [BusinessSafe].[dbo].[AccidentType]([Description], [CreatedBy], [CreatedOn], [LastModifiedBy], [LastModifiedOn], [Deleted] ,[CompanyId])
     VALUES('Stubbed Toe Injury', 'B03C83EE-39F2-4F88-B4C4-7C276B1AAD99', GETDATE(), null, null, 0, 56463)


GO