USE [BusinessSafe]
GO

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_CATALOG = 'BusinessSafe' AND TABLE_NAME = 'EscalationTaskDueTomorrow')
BEGIN
GRANT SELECT,UPDATE,INSERT ON EscalationTaskDueTomorrow TO AllowSelectInsertUpdate
END
GO