--UAT REPORT PERMISSIONS - Do not deploy to live
GRANT EXECUTE ON  [dbo].[SPRPT_BSO_FRAChecklist] TO [AllowAll]
GRANT EXECUTE ON  [dbo].[SPRPT_BSO_GRA] TO [intranetadmin]
GRANT EXECUTE ON  [dbo].[SPRPT_BSO_RAHeader] TO [AllowAll]
GRANT EXECUTE ON  [dbo].[SPRPT_BSO_RAHeader] TO [intranetadmin]
GRANT EXECUTE ON  [dbo].[SPRPT_BSO001_SiteOverview] TO [intranetadmin]
GRANT EXECUTE ON  [dbo].[SPRPT_BSO006_HRA] TO [AllowAll]
GRANT EXECUTE ON  [dbo].[SPRPT_BSO006_HRAHeader] TO [AllowAll]
GRANT EXECUTE ON  [dbo].[SPRPT_BSO006_HRAPictogram] TO [AllowAll]
GRANT EXECUTE ON  [dbo].[SPRPT_BSO007_PRA] TO [AllowAll]
GRANT EXECUTE ON  [dbo].[SPRPT_BSO007_PRAHeader] TO [AllowAll]
GRANT EXECUTE ON  [dbo].[SPRPT_BSO12_FRA] TO [AllowAll]
GRANT EXECUTE ON  [dbo].[SPRPT_BSO12_FRA_FCM] TO [AllowAll]
GRANT EXECUTE ON  [dbo].[SPRPT_BSO12_FRAHeader] TO [AllowAll]