// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.17929
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BusinessSafe.AcceptanceTests.Features.ReassignFurtherActionTasks
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Bulk Reassigning Further Action Tasks From Task List")]
    [NUnit.Framework.CategoryAttribute("BulkReassigningFurtherActionTasks")]
    public partial class BulkReassigningFurtherActionTasksFromTaskListFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BulkReassignFurtherControlMeasureFromTaskList.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Bulk Reassigning Further Action Tasks From Task List", "In order to reassign several further action tasks at a time\r\nAs a business safe o" +
                    "nline user with the correct user access rights\r\nI want to be able to reassign se" +
                    "veral further action tasks to a given user", ProgrammingLanguage.CSharp, new string[] {
                        "BulkReassigningFurtherActionTasks"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line 8
 testRunner.Given("I have logged in as company with id \'55881\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "MultiHazardRiskAssessmentHazardId",
                        "Title",
                        "Description",
                        "Reference",
                        "Deleted",
                        "CreatedOn",
                        "CreatedBy",
                        "TaskAssignedToId",
                        "TaskCompletionDueDate",
                        "TaskStatusId",
                        "TaskCompletedDate",
                        "TaskCompletedComments",
                        "TaskCategoryId",
                        "TaskReoccurringTypeId",
                        "TaskReoccurringEndDate",
                        "Discriminator",
                        "TaskGuid",
                        "SendTaskNotification",
                        "SendTaskCompletedNotification",
                        "SendTaskOverdueNotification"});
            table1.AddRow(new string[] {
                        "29",
                        "Bulk RA FROM List FCM 1",
                        "Description 1",
                        "Bulk_Reassign_From_TaskList_FCM01",
                        "0",
                        "2012-09-13 13:25:28.000",
                        "16ac58fb-4ea4-4482-ac3d-000d607af67c",
                        "9D24AE1A-6645-45FC-9D50-8FC70BABEB89",
                        "2012-09-19 00:00:00.000",
                        "0",
                        "NULL",
                        "NULL",
                        "3",
                        "2",
                        "2012-12-25 00:00:00.000",
                        "MultiHazardRiskAssessmentFurtherControlMeasureTask",
                        "ab751aa0-35e5-4306-a530-32c62404f853",
                        "0",
                        "1",
                        "1"});
            table1.AddRow(new string[] {
                        "29",
                        "Bulk RA FROM List FCM 2",
                        "Description 2",
                        "Bulk_Reassign_From_TaskList_FCM02",
                        "0",
                        "2012-09-13 13:25:28.000",
                        "16ac58fb-4ea4-4482-ac3d-000d607af67c",
                        "9D24AE1A-6645-45FC-9D50-8FC70BABEB89",
                        "2012-09-19 00:00:00.000",
                        "0",
                        "NULL",
                        "NULL",
                        "3",
                        "2",
                        "2012-12-25 00:00:00.000",
                        "MultiHazardRiskAssessmentFurtherControlMeasureTask",
                        "0152ba8b-92f3-402c-8505-5ab5601ebcb4",
                        "0",
                        "1",
                        "1"});
            table1.AddRow(new string[] {
                        "29",
                        "Bulk RA FROM List FCM 3",
                        "Description 3",
                        "Bulk_Reassign_From_TaskList_FCM03",
                        "0",
                        "2012-09-13 13:25:28.000",
                        "16ac58fb-4ea4-4482-ac3d-000d607af67c",
                        "9D24AE1A-6645-45FC-9D50-8FC70BABEB89",
                        "2012-09-19 00:00:00.000",
                        "0",
                        "NULL",
                        "NULL",
                        "3",
                        "2",
                        "2012-12-25 00:00:00.000",
                        "MultiHazardRiskAssessmentFurtherControlMeasureTask",
                        "5e90f428-76c0-4b6f-8939-0d916c145f5f",
                        "0",
                        "1",
                        "1"});
            table1.AddRow(new string[] {
                        "29",
                        "Bulk RA FROM List FCM 4",
                        "Description 4",
                        "Bulk_Reassign_From_TaskList_FCM04",
                        "0",
                        "2012-09-13 13:25:28.000",
                        "16ac58fb-4ea4-4482-ac3d-000d607af67c",
                        "9D24AE1A-6645-45FC-9D50-8FC70BABEB89",
                        "2012-09-19 00:00:00.000",
                        "0",
                        "NULL",
                        "NULL",
                        "3",
                        "2",
                        "2012-12-25 00:00:00.000",
                        "MultiHazardRiskAssessmentFurtherControlMeasureTask",
                        "d07a4628-c743-4c75-bcaa-b65f4396625a",
                        "0",
                        "1",
                        "1"});
            table1.AddRow(new string[] {
                        "29",
                        "Bulk RA FROM List FCM 5",
                        "Description 5",
                        "Bulk_Reassign_From_TaskList_FCM05",
                        "0",
                        "2012-09-13 13:25:28.000",
                        "16ac58fb-4ea4-4482-ac3d-000d607af67c",
                        "9D24AE1A-6645-45FC-9D50-8FC70BABEB89",
                        "2012-09-19 00:00:00.000",
                        "0",
                        "NULL",
                        "NULL",
                        "3",
                        "2",
                        "2012-12-25 00:00:00.000",
                        "MultiHazardRiskAssessmentFurtherControlMeasureTask",
                        "2529b4d8-eca3-4eae-a096-00f5301a6d60",
                        "0",
                        "1",
                        "1"});
            table1.AddRow(new string[] {
                        "29",
                        "Bulk RA FROM List FCM 6",
                        "Description 6",
                        "Bulk_Reassign_From_TaskList_FCM06",
                        "0",
                        "2012-09-13 13:25:28.000",
                        "16ac58fb-4ea4-4482-ac3d-000d607af67c",
                        "9D24AE1A-6645-45FC-9D50-8FC70BABEB89",
                        "2012-09-19 00:00:00.000",
                        "0",
                        "NULL",
                        "NULL",
                        "3",
                        "2",
                        "2012-12-25 00:00:00.000",
                        "MultiHazardRiskAssessmentFurtherControlMeasureTask",
                        "5f977193-229f-432a-ae2b-e89f928b8a35",
                        "0",
                        "1",
                        "1"});
#line 9
 testRunner.And("I have the following tasks:", ((string)(null)), table1, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Reassign several further action tasks to a user from task list")]
        public virtual void ReassignSeveralFurtherActionTasksToAUserFromTaskList()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Reassign several further action tasks to a user from task list", ((string[])(null)));
#line 18
this.ScenarioSetup(scenarioInfo);
#line 7
this.FeatureBackground();
#line 19
 testRunner.Given("I have entered \'Glen Ross\' into the \'Employee\' field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
 testRunner.And("I have entered \'9D24AE1A-6645-45FC-9D50-8FC70BABEB89\' into the \'EmployeeId\' field" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And("user click on GoToTasks for Assigned To Filter", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.And("I press \'btnBulkAssign\' link", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.Then("the task list should be in bulk reassign mode", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 24
 testRunner.Given("I tick task \'Bulk RA FROM List FCM 1\' in the task list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 25
 testRunner.And("I tick task \'Bulk RA FROM List FCM 2\' in the task list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.And("I tick task \'Bulk RA FROM List FCM 3\' in the task list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 27
 testRunner.Given("I have entered \'Kim Howard\' into the \'BulkReassignTo\' field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
 testRunner.And("I have entered \'A433E9B2-84F6-4AD7-A89C-050E914DFF01\' into the \'BulkReassignToId\'" +
                    " field", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.When("I press \'BulkReassignSaveButton\' button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 30
 testRunner.Then("task \'Bulk RA FROM List FCM 1\' is assigned to \'Kim Howard\' in the task list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 31
 testRunner.Then("task \'Bulk RA FROM List FCM 2\' is assigned to \'Kim Howard\' in the task list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 32
 testRunner.Then("task \'Bulk RA FROM List FCM 3\' is assigned to \'Kim Howard\' in the task list", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
